### ISSUE TITLE
Players can take items

### ISSUE THREAD

**Issue by Tabizzz** [RyseInventory/RyseInventory#50]
**Describe the bug**
I'm trying to make an inspect menu that opens when a player right clicks another player, but the player opening the menu can take the menu items, however if I open the menu with commands he can't take the items

**To Reproduce**
1. Create a menu with empty IntelligentItems
2. Open the menu on the listener of a PlayerInteractEntityEvent
3. Try to take items from inventory

**Expected behavior**
Players cant take items from the inventory

**Code (Optional)**
[The Inventory provider](https://github.com/Tabizzz/MonarquiCraft/blob/c4bef662cd004f49d42000a2ffa0e70ddeb6eb69/src/main/java/me/tabizzz/monarquicraft/Menus/InspectMenu.java)

[How i try to open the menu with a player event](https://github.com/Tabizzz/MonarquiCraft/blob/c4bef662cd004f49d42000a2ffa0e70ddeb6eb69/src/main/java/me/tabizzz/monarquicraft/Listeners/EntityListener.java#L23) (players can take items from inventory)

[A command ](https://github.com/Tabizzz/MonarquiCraft/blob/c4bef662cd004f49d42000a2ffa0e70ddeb6eb69/src/main/java/me/tabizzz/monarquicraft/Commands/MonarquiCraftCommand.java#L71) that open the menu and works normally (players cant take items from inventory)

**Additional context**
Is there something I'm forgetting? I even tried to do `Server.dispatchCommand(player, commad)` executing the command to open the menu but even doing it this way items can be taken, I also tried a BukkitRunnable to open the inventory on the next tick and it didn't work either

**Comment by Rysefoxx** [comment]
Weird, I'll definitely take a look at it.

In the meantime, here are a few points that caught my eye:
`private static final RyseInventory Menu = RyseInventory.builder()
			.rows(6)
			.size(54)
			.provider(new InspectMenu())
			.title("Inspeccionando")
			.build(MonarquiCraft.getPlugin());`

Why exactly do you define rows & size? One of them is enough.
Why do you create a new InspectMenu object with new InspectMenu() when the class already implements InventoryProvider? You could just say this.

>  I also tried a BukkitRunnable to open the inventory on the next tick and it didn't work either
This is already done by default.

**Comment by Tabizzz** [comment]
I didn't understand what you mean with the `new InspectMenu()` part, I need a provider for the builder right? How else could I create it?

**Comment by Rysefoxx** [comment]
I have tried a bit. The way you are actually doing it, there should be an exception right when you start the plugin.
Your RyseInventory is a constant that will never change. It is defined during compilation. The problem is that there can be no InventoryManager there yet, because this is initialized only in the Runtime. (You say e.g. in the Main InventoryManager#invoke).

Furthermore there is no reason to define the RyseInventory as a global field. RyseInventory already offers you the possibility to cache the inventories if you don't want them to be completely rebuilt every time.

I'll try to make my highly complicated text clearer with an example:

I have my class "TestProvider" implementing the InventoryProvider. This provider takes care, as you already found out yourself, that items are put into the inventory.
```java
public class TestProvider implements InventoryProvider {
    @Override
    public void init(Player player, InventoryContents contents) {
        contents.set(0, 0, new ItemStack(Material.DIAMOND));
    }
}
```

Furthermore, I have my listener class "TestListener" with the event "PlayerInteractEntityEvent".
```java
public class TestListener implements Listener {

    private final RyseInventoryPlugin plugin;
    private final InventoryManager manager;

    @Contract(pure = true)
    public TestListener(RyseInventoryPlugin plugin, InventoryManager manager) {
        this.plugin = plugin;
        this.manager = manager;
    }

    @EventHandler
    public void onInteract(PlayerInteractEntityEvent event) {
        Optional<RyseInventory> inventory = this.manager.getInventory("TEST");

        if (inventory.isPresent()) {
            inventory.get().open(event.getPlayer());
            return;
        }

        RyseInventory.builder()
                .rows(6)
                .permanentCache()
                .identifier("TEST")
                .provider(new TestProvider())
                .title("Test")
                .build(this.plugin)
                .open(event.getPlayer());
    }
}
```
(Don't forget to register the class in the onEnable and pass the 2 parameters).

I pass via dependency injection my main class and my InventoryManager. (Please distance yourself from Main#getPlugin or Main#getInstance). If the event is fired I search for an inventory with ID "TEST" in which I call the getInventory method in the InventoryManager class. Watch out. This is an overloaded method. The possibility exists also for UUID. If this inventory is already in the cache, the inventory is simply opened. Otherwise we create the inventory. We say with permanentCache that it will be stored permanently (Until reload/restart). If you would omit the permanentCache, **Optional<RyseInventory> inventory = this.manager.getInventory("TEST");** would only return something if a player has the inventory open. Otherwise, we still define the ID as well as provider. Finally we open the inventory for the player. As a result, the player cannot open the inventory.


If you don't quite follow, you can find everything described in details on my documentation -> https://wiki.ryseinventory.de. (Even how to use each method with video copy).

**Comment by Tabizzz** [comment]
hi @Rysefoxx, [i update the builder](https://github.com/Tabizzz/MonarquiCraft/blob/5482885d55a4690fc961a3ed81c2b32175c0e784/src/main/java/me/tabizzz/monarquicraft/Menus/InspectMenuConfig.java) based on your suggestions but the bug still exits but i found something new:

in my code i check if the player is sneaking:
```java
if(event.getPlayer().isSneaking() && event.getPlayer().getInventory().getItemInMainHand().getType() == Material.AIR) {
	InspectMenu.Open(event.getPlayer(), target);
}
```

for testing i removed the sneak check and found that if i open the inventory, with rigth click on a player then i cnat take the items, but for some reason the problem if is the players is sneakin and i open the menu then he can take item, you can test that case?

**Comment by Tabizzz** [comment]
Other information is that it is a purpur 1.17.1 server, I don't know if that affects anything

**Comment by Rysefoxx** [comment]
I tried your sneak condition and there I continue to have no problem.

**Comment by Tabizzz** [comment]
okay thanks for your help @Rysefoxx, i dont know if there is any other plugin causing that or what is hapenning, and the end i solved adding a [listener](https://github.com/Tabizzz/MonarquiCraft/blob/6dff7620cd50ca72a72ea5648d52fbf562e91d3e/src/main/java/me/tabizzz/monarquicraft/Menus/InspectMenu.java#L40) to the builder, for some reason the events are not cancelled when the players is sneaking.
