### ISSUE TITLE
Unable to set the output item of the anvil gui

### ISSUE THREAD

**Issue by Mr-EmPee** [RyseInventory/RyseInventory#51]
Server version: Paper 1.19.3
Lib version: 1.5.6.2
Server is clean

```java
new InventoryProvider() {
      @Override
      public void anvil(Player player, RyseAnvil anvil) {
        anvil.itemLeft(left());
        anvil.itemRight(right());
        anvil.itemOutput(output());
        anvil.onComplete(e -> {
          onComplete(e.getPlayer(), e.getText());
          return Collections.singletonList(AnvilGUI.ResponseAction.close());
        });
      }
};
```
This code sets without any problem the left and right item but the output isn't working.
What am I doing wrong?

**Comment by Rysefoxx** [comment]
You are not doing anything wrong. It just seems that you can't put anything in the output slot if you put something in the left or right slot.
At the end of the day, it's a "normal" inventory where the contents are set with Inventory#setItem. From this I would interpret that Minecraft simply doesn't allow it, because it probably wouldn't make sense.

I wouldn't say it's impossible. But I have my doubts. I'll try to find a solution anyway, but I can't promise anything.

**Comment by Mr-EmPee** [comment]
I see ty for your help, by the way I've just seen that the same issue has been opend on AnvilGUI repo [#237](https://github.com/WesJD/AnvilGUI/issues/237)

**Comment by Rysefoxx** [comment]
Exactly I thought that it is a hard problem. In the end I would have to wait for AnvilGUI. Since the issue has been open on their Github page for a while, I think it will take some time to find a solution.
